Feature/music-genre-table
jaflih/catalog_of_my_things pull request #38
Opened 2022-04-19 14:55 UTC by Debas-31

## Schema for a music album and genre
>In this milestone of the project implemented:
- [x] Create a schema.sql file with tables that will be analogical to the structure of the classes that you created:
   - music_albums table (add all properties and associations from the parent Item class as table columns)
   - genres table

2022-04-19 22:20 UTC, jaflih requested changes
Hi @Debas-31,

Good job !
There are some issues that you still need to work on but you are almost there!

2022-04-19 22:20 UTC, jaflih commented on database/schema.sql
> +  /* name VARCHAR(100),*/
It is advisable to remove commented code so as to make your code cleaner.

2022-04-19 22:20 UTC, jaflih commented on database/schema.sql
> +  id INT,
Each table must have a primary key, so it is better to add it

2022-04-19 22:20 UTC, jaflih commented on database/schema.sql
> +  id INT,
Each table must have a primary key, so it is better to add it

2022-04-19 22:20 UTC, jaflih commented on database/schema.sql
> +  FOREIGN KEY(id) REFERENCES item(id)
to create inheritance in SQL, you can do:
- like @Ginohmk  did: add all mother properties to the child, so here the table `music_albums` must had: `publish_date`, `archived`, `id`  and `on_spotify`
- like I did: use the `INHERITS` keyword  , there is the code that I used : 
```
CREATE TABLE games(
  multiplayer BOOLEAN,
  last_played_at DATE
) INHERITS (Items);
```

2022-04-19 22:20 UTC, jaflih commented on database/schema.sql
> +  FOREIGN KEY(id) REFERENCES item(id)
to create inheritance in SQL, you can do:
- like @Ginohmk  did: add all mother properties to the child, so here the table `music_albums` must had: `publish_date`, `archived`, `id`  and `on_spotify`
- like I did: use the `INHERITS` keyword  , there is the code that I used : 
```
CREATE TABLE games(
  multiplayer BOOLEAN,
  last_played_at DATE
) INHERITS (Items);
```

2022-04-20 05:45 UTC, Debas-31 commented on database/schema.sql
> +  FOREIGN KEY(id) REFERENCES item(id)
Thank you for the feedback. I am not sure whether we can use a foreign key as I did instead of the `INHERITS` keyword.

2022-04-20 08:37 UTC, Ginohmk approved these changes
## Approved 

<hr>

You followed all requirements

2022-04-20 08:40 UTC, jaflih approved these changes
Hi,
Congratulations! 🎉
Your project is complete! There is nothing else to say other than... it's time to merge it 🚀 :

Cheers and Happy coding!👏👏👏

2022-04-20 08:40 UTC, merged