Capstone Project : Catalog of my things
jaflih/catalog_of_my_things pull request #51
Opened 2022-04-21 15:00 UTC by jaflih

**Capstone Project: Catalog of my things**

**SQL**
- Created SQL requests for creating tables: Items, Games, MusicAlbums, Books, Genres, Authors, Labels
- Used primary key & foreign key mechanisms for joining tables.

**Ruby**
- Implemented classes and objects for Items, Games, MusicAlbums, Books, Genres, Authors, Labels
- Build interactive console to: 
   - List Items, Games, MusicAlbums, Books, Genres, Authors, Labels
   - Create Games, MusicAlbums, Books
- Load/Store data in JSON files

**Test**
- Used TDD approach
- Created units tests for all classes 

**Additional requirements**
- When creating a game or a music album you can choose the author, label and genre

2022-04-21 15:53 UTC, eri8-9 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost there](https://media.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-21 15:53 UTC, eri8-9 commented on application/item.rb
> +# rubocop:disable Style/TrivialAccessors
- [ ] You can avoid disabling linters just by using the `attr_accessor` for, :genre, :author, :source and :label. Rubocop refers to a trivial writer method because there is a better way to write code instead of a verbose code.

2022-04-21 21:56 UTC, jaflih commented on application/item.rb
> +# rubocop:disable Style/TrivialAccessors
Ok thank you, we done it

2022-04-21 21:56 UTC, jaflih commented on data/authors.json
> +[{"first_name":"Stephen","last_name":"King"}]
Ok thank you, we done it

2022-04-22 08:10 UTC, mikethreels approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 08:17 UTC, jaflih commented
HI, @mikethreels @eri8-9 
![thanks](https://user-images.githubusercontent.com/7243132/164647320-91eb8a91-4704-47aa-ba58-e1e977eb65f0.jpeg)

2022-04-22 08:17 UTC, merged